version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["area/build"]
    schedule:
      # by default this will be on a monday.
      interval: "weekly"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /tests/azure
    schedule:
      interval: daily
